/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './modules/workspace-shell/app-shell/root-route'
import { Route as modulesAccessPublicEntryPublicLayoutRouteRouteImport } from './modules/access/public-entry/public-layout-route'
import { Route as modulesWorkspaceShellAppShellProtectedRouteRouteImport } from './modules/workspace-shell/app-shell/protected-route'
import { Route as modulesAccessSessionAuthLayoutRouteRouteImport } from './modules/access/session/auth-layout-route'
import { Route as modulesStudyNotesStudyNotesRouteRouteImport } from './modules/study-notes/study-notes-route'
import { Route as modulesAccessSessionSettingsRouteRouteImport } from './modules/access/session/settings-route'
import { Route as modulesRecallRecallRouteRouteImport } from './modules/recall/recall-route'
import { Route as modulesLabelsLabelManagementLabelsRouteRouteImport } from './modules/labels/label-management/labels-route'
import { Route as modulesStudyGuidanceStudyGuidanceRouteRouteImport } from './modules/study-guidance/study-guidance-route'
import { Route as modulesFocusFocusRouteRouteImport } from './modules/focus/focus-route'
import { Route as modulesAccessSessionRegisterRouteRouteImport } from './modules/access/session/register-route'
import { Route as modulesAccessSessionLoginRouteRouteImport } from './modules/access/session/login-route'
import { Route as modulesAccessSessionForgotPasswordRouteRouteImport } from './modules/access/session/forgot-password-route'
import { Route as modulesAccessPublicEntryPublicIndexRouteRouteImport } from './modules/access/public-entry/public-index-route'
import { Route as modulesRecallRecallSessionRouteRouteImport } from './modules/recall/recall-session-route'
import { Route as modulesRecallRecallSelectionRouteRouteImport } from './modules/recall/recall-selection-route'
import { Route as modulesRecallRecallResultsRouteRouteImport } from './modules/recall/recall-results-route'
import { Route as modulesRecallRecallPracticeRepairQueueRouteRouteImport } from './modules/recall/recall-practice-repair-queue-route'
import { Route as modulesRecallRecallResultsWorkspaceRouteRouteImport } from './modules/recall/recall-results-workspace-route'
import { Route as modulesRecallRecallPracticeRepairRouteRouteImport } from './modules/recall/recall-practice-repair-route'
import { Route as modulesRecallRecallPracticeRepairDraftRouteRouteImport } from './modules/recall/recall-practice-repair-draft-route'

const modulesAccessPublicEntryPublicLayoutRouteRoute =
  modulesAccessPublicEntryPublicLayoutRouteRouteImport.update({
    id: '/_public',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesWorkspaceShellAppShellProtectedRouteRoute =
  modulesWorkspaceShellAppShellProtectedRouteRouteImport.update({
    id: '/_protected',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesAccessSessionAuthLayoutRouteRoute =
  modulesAccessSessionAuthLayoutRouteRouteImport.update({
    id: '/_auth',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesStudyNotesStudyNotesRouteRoute =
  modulesStudyNotesStudyNotesRouteRouteImport.update({
    id: '/study-notes',
    path: '/study-notes',
    getParentRoute: () => modulesWorkspaceShellAppShellProtectedRouteRoute,
  } as any)
const modulesAccessSessionSettingsRouteRoute =
  modulesAccessSessionSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => modulesWorkspaceShellAppShellProtectedRouteRoute,
  } as any)
const modulesRecallRecallRouteRoute =
  modulesRecallRecallRouteRouteImport.update({
    id: '/recall',
    path: '/recall',
    getParentRoute: () => modulesWorkspaceShellAppShellProtectedRouteRoute,
  } as any)
const modulesLabelsLabelManagementLabelsRouteRoute =
  modulesLabelsLabelManagementLabelsRouteRouteImport.update({
    id: '/labels',
    path: '/labels',
    getParentRoute: () => modulesWorkspaceShellAppShellProtectedRouteRoute,
  } as any)
const modulesStudyGuidanceStudyGuidanceRouteRoute =
  modulesStudyGuidanceStudyGuidanceRouteRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => modulesWorkspaceShellAppShellProtectedRouteRoute,
  } as any)
const modulesFocusFocusRouteRoute = modulesFocusFocusRouteRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => modulesWorkspaceShellAppShellProtectedRouteRoute,
} as any)
const modulesAccessSessionRegisterRouteRoute =
  modulesAccessSessionRegisterRouteRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => modulesAccessSessionAuthLayoutRouteRoute,
  } as any)
const modulesAccessSessionLoginRouteRoute =
  modulesAccessSessionLoginRouteRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => modulesAccessSessionAuthLayoutRouteRoute,
  } as any)
const modulesAccessSessionForgotPasswordRouteRoute =
  modulesAccessSessionForgotPasswordRouteRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => modulesAccessSessionAuthLayoutRouteRoute,
  } as any)
const modulesAccessPublicEntryPublicIndexRouteRoute =
  modulesAccessPublicEntryPublicIndexRouteRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => modulesAccessPublicEntryPublicLayoutRouteRoute,
  } as any)
const modulesRecallRecallSessionRouteRoute =
  modulesRecallRecallSessionRouteRouteImport.update({
    id: '/session',
    path: '/session',
    getParentRoute: () => modulesRecallRecallRouteRoute,
  } as any)
const modulesRecallRecallSelectionRouteRoute =
  modulesRecallRecallSelectionRouteRouteImport.update({
    id: '/select',
    path: '/select',
    getParentRoute: () => modulesRecallRecallRouteRoute,
  } as any)
const modulesRecallRecallResultsRouteRoute =
  modulesRecallRecallResultsRouteRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => modulesRecallRecallRouteRoute,
  } as any)
const modulesRecallRecallPracticeRepairQueueRouteRoute =
  modulesRecallRecallPracticeRepairQueueRouteRouteImport.update({
    id: '/repair',
    path: '/repair',
    getParentRoute: () => modulesRecallRecallRouteRoute,
  } as any)
const modulesRecallRecallResultsWorkspaceRouteRoute =
  modulesRecallRecallResultsWorkspaceRouteRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => modulesRecallRecallRouteRoute,
  } as any)
const modulesRecallRecallPracticeRepairRouteRoute =
  modulesRecallRecallPracticeRepairRouteRouteImport.update({
    id: '/repair/$practiceRepairEntryId',
    path: '/repair/$practiceRepairEntryId',
    getParentRoute: () => modulesRecallRecallRouteRoute,
  } as any)
const modulesRecallRecallPracticeRepairDraftRouteRoute =
  modulesRecallRecallPracticeRepairDraftRouteRouteImport.update({
    id: '/results/$sessionResultId/questions/$questionResultId/repair',
    path: '/results/$sessionResultId/questions/$questionResultId/repair',
    getParentRoute: () => modulesRecallRecallRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof modulesAccessPublicEntryPublicIndexRouteRoute
  '/forgot-password': typeof modulesAccessSessionForgotPasswordRouteRoute
  '/login': typeof modulesAccessSessionLoginRouteRoute
  '/register': typeof modulesAccessSessionRegisterRouteRoute
  '/focus': typeof modulesFocusFocusRouteRoute
  '/insights': typeof modulesStudyGuidanceStudyGuidanceRouteRoute
  '/labels': typeof modulesLabelsLabelManagementLabelsRouteRoute
  '/recall': typeof modulesRecallRecallRouteRouteWithChildren
  '/settings': typeof modulesAccessSessionSettingsRouteRoute
  '/study-notes': typeof modulesStudyNotesStudyNotesRouteRoute
  '/recall/': typeof modulesRecallRecallResultsWorkspaceRouteRoute
  '/recall/repair': typeof modulesRecallRecallPracticeRepairQueueRouteRoute
  '/recall/results': typeof modulesRecallRecallResultsRouteRoute
  '/recall/select': typeof modulesRecallRecallSelectionRouteRoute
  '/recall/session': typeof modulesRecallRecallSessionRouteRoute
  '/recall/repair/$practiceRepairEntryId': typeof modulesRecallRecallPracticeRepairRouteRoute
  '/recall/results/$sessionResultId/questions/$questionResultId/repair': typeof modulesRecallRecallPracticeRepairDraftRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof modulesAccessPublicEntryPublicIndexRouteRoute
  '/forgot-password': typeof modulesAccessSessionForgotPasswordRouteRoute
  '/login': typeof modulesAccessSessionLoginRouteRoute
  '/register': typeof modulesAccessSessionRegisterRouteRoute
  '/focus': typeof modulesFocusFocusRouteRoute
  '/insights': typeof modulesStudyGuidanceStudyGuidanceRouteRoute
  '/labels': typeof modulesLabelsLabelManagementLabelsRouteRoute
  '/settings': typeof modulesAccessSessionSettingsRouteRoute
  '/study-notes': typeof modulesStudyNotesStudyNotesRouteRoute
  '/recall': typeof modulesRecallRecallResultsWorkspaceRouteRoute
  '/recall/repair': typeof modulesRecallRecallPracticeRepairQueueRouteRoute
  '/recall/results': typeof modulesRecallRecallResultsRouteRoute
  '/recall/select': typeof modulesRecallRecallSelectionRouteRoute
  '/recall/session': typeof modulesRecallRecallSessionRouteRoute
  '/recall/repair/$practiceRepairEntryId': typeof modulesRecallRecallPracticeRepairRouteRoute
  '/recall/results/$sessionResultId/questions/$questionResultId/repair': typeof modulesRecallRecallPracticeRepairDraftRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof modulesAccessSessionAuthLayoutRouteRouteWithChildren
  '/_protected': typeof modulesWorkspaceShellAppShellProtectedRouteRouteWithChildren
  '/_public': typeof modulesAccessPublicEntryPublicLayoutRouteRouteWithChildren
  '/_public/': typeof modulesAccessPublicEntryPublicIndexRouteRoute
  '/_auth/forgot-password': typeof modulesAccessSessionForgotPasswordRouteRoute
  '/_auth/login': typeof modulesAccessSessionLoginRouteRoute
  '/_auth/register': typeof modulesAccessSessionRegisterRouteRoute
  '/_protected/focus': typeof modulesFocusFocusRouteRoute
  '/_protected/insights': typeof modulesStudyGuidanceStudyGuidanceRouteRoute
  '/_protected/labels': typeof modulesLabelsLabelManagementLabelsRouteRoute
  '/_protected/recall': typeof modulesRecallRecallRouteRouteWithChildren
  '/_protected/settings': typeof modulesAccessSessionSettingsRouteRoute
  '/_protected/study-notes': typeof modulesStudyNotesStudyNotesRouteRoute
  '/_protected/recall/': typeof modulesRecallRecallResultsWorkspaceRouteRoute
  '/_protected/recall/repair': typeof modulesRecallRecallPracticeRepairQueueRouteRoute
  '/_protected/recall/results': typeof modulesRecallRecallResultsRouteRoute
  '/_protected/recall/select': typeof modulesRecallRecallSelectionRouteRoute
  '/_protected/recall/session': typeof modulesRecallRecallSessionRouteRoute
  '/_protected/recall/repair/$practiceRepairEntryId': typeof modulesRecallRecallPracticeRepairRouteRoute
  '/_protected/recall/results/$sessionResultId/questions/$questionResultId/repair': typeof modulesRecallRecallPracticeRepairDraftRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/focus'
    | '/insights'
    | '/labels'
    | '/recall'
    | '/settings'
    | '/study-notes'
    | '/recall/'
    | '/recall/repair'
    | '/recall/results'
    | '/recall/select'
    | '/recall/session'
    | '/recall/repair/$practiceRepairEntryId'
    | '/recall/results/$sessionResultId/questions/$questionResultId/repair'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/focus'
    | '/insights'
    | '/labels'
    | '/settings'
    | '/study-notes'
    | '/recall'
    | '/recall/repair'
    | '/recall/results'
    | '/recall/select'
    | '/recall/session'
    | '/recall/repair/$practiceRepairEntryId'
    | '/recall/results/$sessionResultId/questions/$questionResultId/repair'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/_public/'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/focus'
    | '/_protected/insights'
    | '/_protected/labels'
    | '/_protected/recall'
    | '/_protected/settings'
    | '/_protected/study-notes'
    | '/_protected/recall/'
    | '/_protected/recall/repair'
    | '/_protected/recall/results'
    | '/_protected/recall/select'
    | '/_protected/recall/session'
    | '/_protected/recall/repair/$practiceRepairEntryId'
    | '/_protected/recall/results/$sessionResultId/questions/$questionResultId/repair'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  modulesAccessSessionAuthLayoutRouteRoute: typeof modulesAccessSessionAuthLayoutRouteRouteWithChildren
  modulesWorkspaceShellAppShellProtectedRouteRoute: typeof modulesWorkspaceShellAppShellProtectedRouteRouteWithChildren
  modulesAccessPublicEntryPublicLayoutRouteRoute: typeof modulesAccessPublicEntryPublicLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof modulesAccessPublicEntryPublicLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof modulesWorkspaceShellAppShellProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof modulesAccessSessionAuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/study-notes': {
      id: '/_protected/study-notes'
      path: '/study-notes'
      fullPath: '/study-notes'
      preLoaderRoute: typeof modulesStudyNotesStudyNotesRouteRouteImport
      parentRoute: typeof modulesWorkspaceShellAppShellProtectedRouteRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof modulesAccessSessionSettingsRouteRouteImport
      parentRoute: typeof modulesWorkspaceShellAppShellProtectedRouteRoute
    }
    '/_protected/recall': {
      id: '/_protected/recall'
      path: '/recall'
      fullPath: '/recall'
      preLoaderRoute: typeof modulesRecallRecallRouteRouteImport
      parentRoute: typeof modulesWorkspaceShellAppShellProtectedRouteRoute
    }
    '/_protected/labels': {
      id: '/_protected/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof modulesLabelsLabelManagementLabelsRouteRouteImport
      parentRoute: typeof modulesWorkspaceShellAppShellProtectedRouteRoute
    }
    '/_protected/insights': {
      id: '/_protected/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof modulesStudyGuidanceStudyGuidanceRouteRouteImport
      parentRoute: typeof modulesWorkspaceShellAppShellProtectedRouteRoute
    }
    '/_protected/focus': {
      id: '/_protected/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof modulesFocusFocusRouteRouteImport
      parentRoute: typeof modulesWorkspaceShellAppShellProtectedRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof modulesAccessSessionRegisterRouteRouteImport
      parentRoute: typeof modulesAccessSessionAuthLayoutRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof modulesAccessSessionLoginRouteRouteImport
      parentRoute: typeof modulesAccessSessionAuthLayoutRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof modulesAccessSessionForgotPasswordRouteRouteImport
      parentRoute: typeof modulesAccessSessionAuthLayoutRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof modulesAccessPublicEntryPublicIndexRouteRouteImport
      parentRoute: typeof modulesAccessPublicEntryPublicLayoutRouteRoute
    }
    '/_protected/recall/session': {
      id: '/_protected/recall/session'
      path: '/session'
      fullPath: '/recall/session'
      preLoaderRoute: typeof modulesRecallRecallSessionRouteRouteImport
      parentRoute: typeof modulesRecallRecallRouteRoute
    }
    '/_protected/recall/select': {
      id: '/_protected/recall/select'
      path: '/select'
      fullPath: '/recall/select'
      preLoaderRoute: typeof modulesRecallRecallSelectionRouteRouteImport
      parentRoute: typeof modulesRecallRecallRouteRoute
    }
    '/_protected/recall/results': {
      id: '/_protected/recall/results'
      path: '/results'
      fullPath: '/recall/results'
      preLoaderRoute: typeof modulesRecallRecallResultsRouteRouteImport
      parentRoute: typeof modulesRecallRecallRouteRoute
    }
    '/_protected/recall/repair': {
      id: '/_protected/recall/repair'
      path: '/repair'
      fullPath: '/recall/repair'
      preLoaderRoute: typeof modulesRecallRecallPracticeRepairQueueRouteRouteImport
      parentRoute: typeof modulesRecallRecallRouteRoute
    }
    '/_protected/recall/': {
      id: '/_protected/recall/'
      path: '/'
      fullPath: '/recall/'
      preLoaderRoute: typeof modulesRecallRecallResultsWorkspaceRouteRouteImport
      parentRoute: typeof modulesRecallRecallRouteRoute
    }
    '/_protected/recall/repair/$practiceRepairEntryId': {
      id: '/_protected/recall/repair/$practiceRepairEntryId'
      path: '/repair/$practiceRepairEntryId'
      fullPath: '/recall/repair/$practiceRepairEntryId'
      preLoaderRoute: typeof modulesRecallRecallPracticeRepairRouteRouteImport
      parentRoute: typeof modulesRecallRecallRouteRoute
    }
    '/_protected/recall/results/$sessionResultId/questions/$questionResultId/repair': {
      id: '/_protected/recall/results/$sessionResultId/questions/$questionResultId/repair'
      path: '/results/$sessionResultId/questions/$questionResultId/repair'
      fullPath: '/recall/results/$sessionResultId/questions/$questionResultId/repair'
      preLoaderRoute: typeof modulesRecallRecallPracticeRepairDraftRouteRouteImport
      parentRoute: typeof modulesRecallRecallRouteRoute
    }
  }
}

interface modulesAccessSessionAuthLayoutRouteRouteChildren {
  modulesAccessSessionForgotPasswordRouteRoute: typeof modulesAccessSessionForgotPasswordRouteRoute
  modulesAccessSessionLoginRouteRoute: typeof modulesAccessSessionLoginRouteRoute
  modulesAccessSessionRegisterRouteRoute: typeof modulesAccessSessionRegisterRouteRoute
}

const modulesAccessSessionAuthLayoutRouteRouteChildren: modulesAccessSessionAuthLayoutRouteRouteChildren =
  {
    modulesAccessSessionForgotPasswordRouteRoute:
      modulesAccessSessionForgotPasswordRouteRoute,
    modulesAccessSessionLoginRouteRoute: modulesAccessSessionLoginRouteRoute,
    modulesAccessSessionRegisterRouteRoute:
      modulesAccessSessionRegisterRouteRoute,
  }

const modulesAccessSessionAuthLayoutRouteRouteWithChildren =
  modulesAccessSessionAuthLayoutRouteRoute._addFileChildren(
    modulesAccessSessionAuthLayoutRouteRouteChildren,
  )

interface modulesRecallRecallRouteRouteChildren {
  modulesRecallRecallResultsWorkspaceRouteRoute: typeof modulesRecallRecallResultsWorkspaceRouteRoute
  modulesRecallRecallPracticeRepairQueueRouteRoute: typeof modulesRecallRecallPracticeRepairQueueRouteRoute
  modulesRecallRecallResultsRouteRoute: typeof modulesRecallRecallResultsRouteRoute
  modulesRecallRecallSelectionRouteRoute: typeof modulesRecallRecallSelectionRouteRoute
  modulesRecallRecallSessionRouteRoute: typeof modulesRecallRecallSessionRouteRoute
  modulesRecallRecallPracticeRepairRouteRoute: typeof modulesRecallRecallPracticeRepairRouteRoute
  modulesRecallRecallPracticeRepairDraftRouteRoute: typeof modulesRecallRecallPracticeRepairDraftRouteRoute
}

const modulesRecallRecallRouteRouteChildren: modulesRecallRecallRouteRouteChildren =
  {
    modulesRecallRecallResultsWorkspaceRouteRoute:
      modulesRecallRecallResultsWorkspaceRouteRoute,
    modulesRecallRecallPracticeRepairQueueRouteRoute:
      modulesRecallRecallPracticeRepairQueueRouteRoute,
    modulesRecallRecallResultsRouteRoute: modulesRecallRecallResultsRouteRoute,
    modulesRecallRecallSelectionRouteRoute:
      modulesRecallRecallSelectionRouteRoute,
    modulesRecallRecallSessionRouteRoute: modulesRecallRecallSessionRouteRoute,
    modulesRecallRecallPracticeRepairRouteRoute:
      modulesRecallRecallPracticeRepairRouteRoute,
    modulesRecallRecallPracticeRepairDraftRouteRoute:
      modulesRecallRecallPracticeRepairDraftRouteRoute,
  }

const modulesRecallRecallRouteRouteWithChildren =
  modulesRecallRecallRouteRoute._addFileChildren(
    modulesRecallRecallRouteRouteChildren,
  )

interface modulesWorkspaceShellAppShellProtectedRouteRouteChildren {
  modulesFocusFocusRouteRoute: typeof modulesFocusFocusRouteRoute
  modulesStudyGuidanceStudyGuidanceRouteRoute: typeof modulesStudyGuidanceStudyGuidanceRouteRoute
  modulesLabelsLabelManagementLabelsRouteRoute: typeof modulesLabelsLabelManagementLabelsRouteRoute
  modulesRecallRecallRouteRoute: typeof modulesRecallRecallRouteRouteWithChildren
  modulesAccessSessionSettingsRouteRoute: typeof modulesAccessSessionSettingsRouteRoute
  modulesStudyNotesStudyNotesRouteRoute: typeof modulesStudyNotesStudyNotesRouteRoute
}

const modulesWorkspaceShellAppShellProtectedRouteRouteChildren: modulesWorkspaceShellAppShellProtectedRouteRouteChildren =
  {
    modulesFocusFocusRouteRoute: modulesFocusFocusRouteRoute,
    modulesStudyGuidanceStudyGuidanceRouteRoute:
      modulesStudyGuidanceStudyGuidanceRouteRoute,
    modulesLabelsLabelManagementLabelsRouteRoute:
      modulesLabelsLabelManagementLabelsRouteRoute,
    modulesRecallRecallRouteRoute: modulesRecallRecallRouteRouteWithChildren,
    modulesAccessSessionSettingsRouteRoute:
      modulesAccessSessionSettingsRouteRoute,
    modulesStudyNotesStudyNotesRouteRoute:
      modulesStudyNotesStudyNotesRouteRoute,
  }

const modulesWorkspaceShellAppShellProtectedRouteRouteWithChildren =
  modulesWorkspaceShellAppShellProtectedRouteRoute._addFileChildren(
    modulesWorkspaceShellAppShellProtectedRouteRouteChildren,
  )

interface modulesAccessPublicEntryPublicLayoutRouteRouteChildren {
  modulesAccessPublicEntryPublicIndexRouteRoute: typeof modulesAccessPublicEntryPublicIndexRouteRoute
}

const modulesAccessPublicEntryPublicLayoutRouteRouteChildren: modulesAccessPublicEntryPublicLayoutRouteRouteChildren =
  {
    modulesAccessPublicEntryPublicIndexRouteRoute:
      modulesAccessPublicEntryPublicIndexRouteRoute,
  }

const modulesAccessPublicEntryPublicLayoutRouteRouteWithChildren =
  modulesAccessPublicEntryPublicLayoutRouteRoute._addFileChildren(
    modulesAccessPublicEntryPublicLayoutRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  modulesAccessSessionAuthLayoutRouteRoute:
    modulesAccessSessionAuthLayoutRouteRouteWithChildren,
  modulesWorkspaceShellAppShellProtectedRouteRoute:
    modulesWorkspaceShellAppShellProtectedRouteRouteWithChildren,
  modulesAccessPublicEntryPublicLayoutRouteRoute:
    modulesAccessPublicEntryPublicLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
