/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected.settings'
import { Route as ProtectedRecallRouteImport } from './routes/_protected.recall'
import { Route as ProtectedNotesRouteImport } from './routes/_protected.notes'
import { Route as ProtectedLabelsRouteImport } from './routes/_protected.labels'
import { Route as ProtectedHistoryRouteImport } from './routes/_protected.history'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as ProtectedNotesRecallRouteImport } from './routes/_protected.notes.recall'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRecallRoute = ProtectedRecallRouteImport.update({
  id: '/recall',
  path: '/recall',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNotesRoute = ProtectedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLabelsRoute = ProtectedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHistoryRoute = ProtectedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedNotesRecallRoute = ProtectedNotesRecallRouteImport.update({
  id: '/recall',
  path: '/recall',
  getParentRoute: () => ProtectedNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/history': typeof ProtectedHistoryRoute
  '/labels': typeof ProtectedLabelsRoute
  '/notes': typeof ProtectedNotesRouteWithChildren
  '/recall': typeof ProtectedRecallRoute
  '/settings': typeof ProtectedSettingsRoute
  '/notes/recall': typeof ProtectedNotesRecallRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/history': typeof ProtectedHistoryRoute
  '/labels': typeof ProtectedLabelsRoute
  '/notes': typeof ProtectedNotesRouteWithChildren
  '/recall': typeof ProtectedRecallRoute
  '/settings': typeof ProtectedSettingsRoute
  '/notes/recall': typeof ProtectedNotesRecallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_protected/history': typeof ProtectedHistoryRoute
  '/_protected/labels': typeof ProtectedLabelsRoute
  '/_protected/notes': typeof ProtectedNotesRouteWithChildren
  '/_protected/recall': typeof ProtectedRecallRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/notes/recall': typeof ProtectedNotesRecallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/history'
    | '/labels'
    | '/notes'
    | '/recall'
    | '/settings'
    | '/notes/recall'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/history'
    | '/labels'
    | '/notes'
    | '/recall'
    | '/settings'
    | '/notes/recall'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/history'
    | '/_protected/labels'
    | '/_protected/notes'
    | '/_protected/recall'
    | '/_protected/settings'
    | '/_public/'
    | '/_protected/notes/recall'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/recall': {
      id: '/_protected/recall'
      path: '/recall'
      fullPath: '/recall'
      preLoaderRoute: typeof ProtectedRecallRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/notes': {
      id: '/_protected/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof ProtectedNotesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/labels': {
      id: '/_protected/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof ProtectedLabelsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/history': {
      id: '/_protected/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ProtectedHistoryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/notes/recall': {
      id: '/_protected/notes/recall'
      path: '/recall'
      fullPath: '/notes/recall'
      preLoaderRoute: typeof ProtectedNotesRecallRouteImport
      parentRoute: typeof ProtectedNotesRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedNotesRouteChildren {
  ProtectedNotesRecallRoute: typeof ProtectedNotesRecallRoute
}

const ProtectedNotesRouteChildren: ProtectedNotesRouteChildren = {
  ProtectedNotesRecallRoute: ProtectedNotesRecallRoute,
}

const ProtectedNotesRouteWithChildren = ProtectedNotesRoute._addFileChildren(
  ProtectedNotesRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedHistoryRoute: typeof ProtectedHistoryRoute
  ProtectedLabelsRoute: typeof ProtectedLabelsRoute
  ProtectedNotesRoute: typeof ProtectedNotesRouteWithChildren
  ProtectedRecallRoute: typeof ProtectedRecallRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedHistoryRoute: ProtectedHistoryRoute,
  ProtectedLabelsRoute: ProtectedLabelsRoute,
  ProtectedNotesRoute: ProtectedNotesRouteWithChildren,
  ProtectedRecallRoute: ProtectedRecallRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
