/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './modules/workspace-shell/routes/root-route'
import { Route as modulesAccessRoutesPublicLayoutRouteRouteImport } from './modules/access/routes/public-layout-route'
import { Route as modulesWorkspaceShellRoutesProtectedRouteRouteImport } from './modules/workspace-shell/routes/protected-route'
import { Route as modulesAccessRoutesAuthLayoutRouteRouteImport } from './modules/access/routes/auth-layout-route'
import { Route as modulesAccessRoutesSettingsRouteRouteImport } from './modules/access/routes/settings-route'
import { Route as modulesLearningLoopRecallRecallRouteRouteImport } from './modules/learning-loop/recall/recall-route'
import { Route as modulesLearningLoopNotesWorkspaceNotesRouteRouteImport } from './modules/learning-loop/notes-workspace/notes-route'
import { Route as modulesLabelsRoutesLabelsRouteRouteImport } from './modules/labels/routes/labels-route'
import { Route as modulesLearningLoopFocusFocusRouteRouteImport } from './modules/learning-loop/focus/focus-route'
import { Route as modulesAccessRoutesRegisterRouteRouteImport } from './modules/access/routes/register-route'
import { Route as modulesAccessRoutesLoginRouteRouteImport } from './modules/access/routes/login-route'
import { Route as modulesAccessRoutesForgotPasswordRouteRouteImport } from './modules/access/routes/forgot-password-route'
import { Route as modulesAccessRoutesPublicIndexRouteRouteImport } from './modules/access/routes/public-index-route'
import { Route as modulesLearningLoopRecallRecallSessionRouteRouteImport } from './modules/learning-loop/recall/recall-session-route'
import { Route as modulesLearningLoopRecallRecallSelectionRouteRouteImport } from './modules/learning-loop/recall/recall-selection-route'
import { Route as modulesLearningLoopRecallRecallResultsWorkspaceRouteRouteImport } from './modules/learning-loop/recall/recall-results-workspace-route'

const modulesAccessRoutesPublicLayoutRouteRoute =
  modulesAccessRoutesPublicLayoutRouteRouteImport.update({
    id: '/_public',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesWorkspaceShellRoutesProtectedRouteRoute =
  modulesWorkspaceShellRoutesProtectedRouteRouteImport.update({
    id: '/_protected',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesAccessRoutesAuthLayoutRouteRoute =
  modulesAccessRoutesAuthLayoutRouteRouteImport.update({
    id: '/_auth',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesAccessRoutesSettingsRouteRoute =
  modulesAccessRoutesSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => modulesWorkspaceShellRoutesProtectedRouteRoute,
  } as any)
const modulesLearningLoopRecallRecallRouteRoute =
  modulesLearningLoopRecallRecallRouteRouteImport.update({
    id: '/recall',
    path: '/recall',
    getParentRoute: () => modulesWorkspaceShellRoutesProtectedRouteRoute,
  } as any)
const modulesLearningLoopNotesWorkspaceNotesRouteRoute =
  modulesLearningLoopNotesWorkspaceNotesRouteRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => modulesWorkspaceShellRoutesProtectedRouteRoute,
  } as any)
const modulesLabelsRoutesLabelsRouteRoute =
  modulesLabelsRoutesLabelsRouteRouteImport.update({
    id: '/labels',
    path: '/labels',
    getParentRoute: () => modulesWorkspaceShellRoutesProtectedRouteRoute,
  } as any)
const modulesLearningLoopFocusFocusRouteRoute =
  modulesLearningLoopFocusFocusRouteRouteImport.update({
    id: '/focus',
    path: '/focus',
    getParentRoute: () => modulesWorkspaceShellRoutesProtectedRouteRoute,
  } as any)
const modulesAccessRoutesRegisterRouteRoute =
  modulesAccessRoutesRegisterRouteRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => modulesAccessRoutesAuthLayoutRouteRoute,
  } as any)
const modulesAccessRoutesLoginRouteRoute =
  modulesAccessRoutesLoginRouteRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => modulesAccessRoutesAuthLayoutRouteRoute,
  } as any)
const modulesAccessRoutesForgotPasswordRouteRoute =
  modulesAccessRoutesForgotPasswordRouteRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => modulesAccessRoutesAuthLayoutRouteRoute,
  } as any)
const modulesAccessRoutesPublicIndexRouteRoute =
  modulesAccessRoutesPublicIndexRouteRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => modulesAccessRoutesPublicLayoutRouteRoute,
  } as any)
const modulesLearningLoopRecallRecallSessionRouteRoute =
  modulesLearningLoopRecallRecallSessionRouteRouteImport.update({
    id: '/session',
    path: '/session',
    getParentRoute: () => modulesLearningLoopRecallRecallRouteRoute,
  } as any)
const modulesLearningLoopRecallRecallSelectionRouteRoute =
  modulesLearningLoopRecallRecallSelectionRouteRouteImport.update({
    id: '/select',
    path: '/select',
    getParentRoute: () => modulesLearningLoopRecallRecallRouteRoute,
  } as any)
const modulesLearningLoopRecallRecallResultsWorkspaceRouteRoute =
  modulesLearningLoopRecallRecallResultsWorkspaceRouteRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => modulesLearningLoopRecallRecallRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof modulesAccessRoutesPublicIndexRouteRoute
  '/forgot-password': typeof modulesAccessRoutesForgotPasswordRouteRoute
  '/login': typeof modulesAccessRoutesLoginRouteRoute
  '/register': typeof modulesAccessRoutesRegisterRouteRoute
  '/focus': typeof modulesLearningLoopFocusFocusRouteRoute
  '/labels': typeof modulesLabelsRoutesLabelsRouteRoute
  '/notes': typeof modulesLearningLoopNotesWorkspaceNotesRouteRoute
  '/recall': typeof modulesLearningLoopRecallRecallRouteRouteWithChildren
  '/settings': typeof modulesAccessRoutesSettingsRouteRoute
  '/recall/': typeof modulesLearningLoopRecallRecallResultsWorkspaceRouteRoute
  '/recall/select': typeof modulesLearningLoopRecallRecallSelectionRouteRoute
  '/recall/session': typeof modulesLearningLoopRecallRecallSessionRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof modulesAccessRoutesPublicIndexRouteRoute
  '/forgot-password': typeof modulesAccessRoutesForgotPasswordRouteRoute
  '/login': typeof modulesAccessRoutesLoginRouteRoute
  '/register': typeof modulesAccessRoutesRegisterRouteRoute
  '/focus': typeof modulesLearningLoopFocusFocusRouteRoute
  '/labels': typeof modulesLabelsRoutesLabelsRouteRoute
  '/notes': typeof modulesLearningLoopNotesWorkspaceNotesRouteRoute
  '/settings': typeof modulesAccessRoutesSettingsRouteRoute
  '/recall': typeof modulesLearningLoopRecallRecallResultsWorkspaceRouteRoute
  '/recall/select': typeof modulesLearningLoopRecallRecallSelectionRouteRoute
  '/recall/session': typeof modulesLearningLoopRecallRecallSessionRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof modulesAccessRoutesAuthLayoutRouteRouteWithChildren
  '/_protected': typeof modulesWorkspaceShellRoutesProtectedRouteRouteWithChildren
  '/_public': typeof modulesAccessRoutesPublicLayoutRouteRouteWithChildren
  '/_public/': typeof modulesAccessRoutesPublicIndexRouteRoute
  '/_auth/forgot-password': typeof modulesAccessRoutesForgotPasswordRouteRoute
  '/_auth/login': typeof modulesAccessRoutesLoginRouteRoute
  '/_auth/register': typeof modulesAccessRoutesRegisterRouteRoute
  '/_protected/focus': typeof modulesLearningLoopFocusFocusRouteRoute
  '/_protected/labels': typeof modulesLabelsRoutesLabelsRouteRoute
  '/_protected/notes': typeof modulesLearningLoopNotesWorkspaceNotesRouteRoute
  '/_protected/recall': typeof modulesLearningLoopRecallRecallRouteRouteWithChildren
  '/_protected/settings': typeof modulesAccessRoutesSettingsRouteRoute
  '/_protected/recall/': typeof modulesLearningLoopRecallRecallResultsWorkspaceRouteRoute
  '/_protected/recall/select': typeof modulesLearningLoopRecallRecallSelectionRouteRoute
  '/_protected/recall/session': typeof modulesLearningLoopRecallRecallSessionRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/focus'
    | '/labels'
    | '/notes'
    | '/recall'
    | '/settings'
    | '/recall/'
    | '/recall/select'
    | '/recall/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/focus'
    | '/labels'
    | '/notes'
    | '/settings'
    | '/recall'
    | '/recall/select'
    | '/recall/session'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/_public/'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/focus'
    | '/_protected/labels'
    | '/_protected/notes'
    | '/_protected/recall'
    | '/_protected/settings'
    | '/_protected/recall/'
    | '/_protected/recall/select'
    | '/_protected/recall/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  modulesAccessRoutesAuthLayoutRouteRoute: typeof modulesAccessRoutesAuthLayoutRouteRouteWithChildren
  modulesWorkspaceShellRoutesProtectedRouteRoute: typeof modulesWorkspaceShellRoutesProtectedRouteRouteWithChildren
  modulesAccessRoutesPublicLayoutRouteRoute: typeof modulesAccessRoutesPublicLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof modulesAccessRoutesPublicLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof modulesWorkspaceShellRoutesProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof modulesAccessRoutesAuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof modulesAccessRoutesSettingsRouteRouteImport
      parentRoute: typeof modulesWorkspaceShellRoutesProtectedRouteRoute
    }
    '/_protected/recall': {
      id: '/_protected/recall'
      path: '/recall'
      fullPath: '/recall'
      preLoaderRoute: typeof modulesLearningLoopRecallRecallRouteRouteImport
      parentRoute: typeof modulesWorkspaceShellRoutesProtectedRouteRoute
    }
    '/_protected/notes': {
      id: '/_protected/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof modulesLearningLoopNotesWorkspaceNotesRouteRouteImport
      parentRoute: typeof modulesWorkspaceShellRoutesProtectedRouteRoute
    }
    '/_protected/labels': {
      id: '/_protected/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof modulesLabelsRoutesLabelsRouteRouteImport
      parentRoute: typeof modulesWorkspaceShellRoutesProtectedRouteRoute
    }
    '/_protected/focus': {
      id: '/_protected/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof modulesLearningLoopFocusFocusRouteRouteImport
      parentRoute: typeof modulesWorkspaceShellRoutesProtectedRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof modulesAccessRoutesRegisterRouteRouteImport
      parentRoute: typeof modulesAccessRoutesAuthLayoutRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof modulesAccessRoutesLoginRouteRouteImport
      parentRoute: typeof modulesAccessRoutesAuthLayoutRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof modulesAccessRoutesForgotPasswordRouteRouteImport
      parentRoute: typeof modulesAccessRoutesAuthLayoutRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof modulesAccessRoutesPublicIndexRouteRouteImport
      parentRoute: typeof modulesAccessRoutesPublicLayoutRouteRoute
    }
    '/_protected/recall/session': {
      id: '/_protected/recall/session'
      path: '/session'
      fullPath: '/recall/session'
      preLoaderRoute: typeof modulesLearningLoopRecallRecallSessionRouteRouteImport
      parentRoute: typeof modulesLearningLoopRecallRecallRouteRoute
    }
    '/_protected/recall/select': {
      id: '/_protected/recall/select'
      path: '/select'
      fullPath: '/recall/select'
      preLoaderRoute: typeof modulesLearningLoopRecallRecallSelectionRouteRouteImport
      parentRoute: typeof modulesLearningLoopRecallRecallRouteRoute
    }
    '/_protected/recall/': {
      id: '/_protected/recall/'
      path: '/'
      fullPath: '/recall/'
      preLoaderRoute: typeof modulesLearningLoopRecallRecallResultsWorkspaceRouteRouteImport
      parentRoute: typeof modulesLearningLoopRecallRecallRouteRoute
    }
  }
}

interface modulesAccessRoutesAuthLayoutRouteRouteChildren {
  modulesAccessRoutesForgotPasswordRouteRoute: typeof modulesAccessRoutesForgotPasswordRouteRoute
  modulesAccessRoutesLoginRouteRoute: typeof modulesAccessRoutesLoginRouteRoute
  modulesAccessRoutesRegisterRouteRoute: typeof modulesAccessRoutesRegisterRouteRoute
}

const modulesAccessRoutesAuthLayoutRouteRouteChildren: modulesAccessRoutesAuthLayoutRouteRouteChildren =
  {
    modulesAccessRoutesForgotPasswordRouteRoute:
      modulesAccessRoutesForgotPasswordRouteRoute,
    modulesAccessRoutesLoginRouteRoute: modulesAccessRoutesLoginRouteRoute,
    modulesAccessRoutesRegisterRouteRoute:
      modulesAccessRoutesRegisterRouteRoute,
  }

const modulesAccessRoutesAuthLayoutRouteRouteWithChildren =
  modulesAccessRoutesAuthLayoutRouteRoute._addFileChildren(
    modulesAccessRoutesAuthLayoutRouteRouteChildren,
  )

interface modulesLearningLoopRecallRecallRouteRouteChildren {
  modulesLearningLoopRecallRecallResultsWorkspaceRouteRoute: typeof modulesLearningLoopRecallRecallResultsWorkspaceRouteRoute
  modulesLearningLoopRecallRecallSelectionRouteRoute: typeof modulesLearningLoopRecallRecallSelectionRouteRoute
  modulesLearningLoopRecallRecallSessionRouteRoute: typeof modulesLearningLoopRecallRecallSessionRouteRoute
}

const modulesLearningLoopRecallRecallRouteRouteChildren: modulesLearningLoopRecallRecallRouteRouteChildren =
  {
    modulesLearningLoopRecallRecallResultsWorkspaceRouteRoute:
      modulesLearningLoopRecallRecallResultsWorkspaceRouteRoute,
    modulesLearningLoopRecallRecallSelectionRouteRoute:
      modulesLearningLoopRecallRecallSelectionRouteRoute,
    modulesLearningLoopRecallRecallSessionRouteRoute:
      modulesLearningLoopRecallRecallSessionRouteRoute,
  }

const modulesLearningLoopRecallRecallRouteRouteWithChildren =
  modulesLearningLoopRecallRecallRouteRoute._addFileChildren(
    modulesLearningLoopRecallRecallRouteRouteChildren,
  )

interface modulesWorkspaceShellRoutesProtectedRouteRouteChildren {
  modulesLearningLoopFocusFocusRouteRoute: typeof modulesLearningLoopFocusFocusRouteRoute
  modulesLabelsRoutesLabelsRouteRoute: typeof modulesLabelsRoutesLabelsRouteRoute
  modulesLearningLoopNotesWorkspaceNotesRouteRoute: typeof modulesLearningLoopNotesWorkspaceNotesRouteRoute
  modulesLearningLoopRecallRecallRouteRoute: typeof modulesLearningLoopRecallRecallRouteRouteWithChildren
  modulesAccessRoutesSettingsRouteRoute: typeof modulesAccessRoutesSettingsRouteRoute
}

const modulesWorkspaceShellRoutesProtectedRouteRouteChildren: modulesWorkspaceShellRoutesProtectedRouteRouteChildren =
  {
    modulesLearningLoopFocusFocusRouteRoute:
      modulesLearningLoopFocusFocusRouteRoute,
    modulesLabelsRoutesLabelsRouteRoute: modulesLabelsRoutesLabelsRouteRoute,
    modulesLearningLoopNotesWorkspaceNotesRouteRoute:
      modulesLearningLoopNotesWorkspaceNotesRouteRoute,
    modulesLearningLoopRecallRecallRouteRoute:
      modulesLearningLoopRecallRecallRouteRouteWithChildren,
    modulesAccessRoutesSettingsRouteRoute:
      modulesAccessRoutesSettingsRouteRoute,
  }

const modulesWorkspaceShellRoutesProtectedRouteRouteWithChildren =
  modulesWorkspaceShellRoutesProtectedRouteRoute._addFileChildren(
    modulesWorkspaceShellRoutesProtectedRouteRouteChildren,
  )

interface modulesAccessRoutesPublicLayoutRouteRouteChildren {
  modulesAccessRoutesPublicIndexRouteRoute: typeof modulesAccessRoutesPublicIndexRouteRoute
}

const modulesAccessRoutesPublicLayoutRouteRouteChildren: modulesAccessRoutesPublicLayoutRouteRouteChildren =
  {
    modulesAccessRoutesPublicIndexRouteRoute:
      modulesAccessRoutesPublicIndexRouteRoute,
  }

const modulesAccessRoutesPublicLayoutRouteRouteWithChildren =
  modulesAccessRoutesPublicLayoutRouteRoute._addFileChildren(
    modulesAccessRoutesPublicLayoutRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  modulesAccessRoutesAuthLayoutRouteRoute:
    modulesAccessRoutesAuthLayoutRouteRouteWithChildren,
  modulesWorkspaceShellRoutesProtectedRouteRoute:
    modulesWorkspaceShellRoutesProtectedRouteRouteWithChildren,
  modulesAccessRoutesPublicLayoutRouteRoute:
    modulesAccessRoutesPublicLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
